# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json

version: 2

updates:

  - package-ecosystem: 'github-actions'
    directory: "/"
    schedule:
      interval: 'daily'
      time: '01:45'
      timezone: 'Europe/London'
    open-pull-requests-limit: 1
    commit-message:
      prefix: "Upgraded"
      prefix-development: "Upgraded"

  - package-ecosystem: composer
    directory: "/"
    registries: "*"
    schedule:
      interval: daily
      time: "02:20"
      timezone: "Europe/London"
    versioning-strategy: increase
    open-pull-requests-limit: 1
    commit-message:
      prefix: "Upgraded"
      prefix-development: "Upgraded"

  - package-ecosystem: composer
    directory: "/tools/"
    registries: "*"
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/London"
    versioning-strategy: increase
    open-pull-requests-limit: 1
    commit-message:
      prefix: "Upgraded"
      prefix-development: "Upgraded"
